### PR TITLE
Update nl.js

### PR DESCRIPTION
**Pull request by sv3nnie**

### CODE REVIEW

**Comment by Dwynr** [comment]
Hey!

I've added a few more strings to translate last release. Is it possible for you to add those to your PR aswell? Thank you :)

**Comment by sv3nnie** [comment]
I believe they're all in there if I compare the amount of lines the en.js has, and mine has. Check the first commit I did. 😄 
https://github.com/Dwynr/filen-app/pull/10/commits/daae35a8cccfc0f2fa2b722e3512529e2b96e14c

**Comment by Dwynr** [comment]
Yes you are right! I am sorry, I forgot to push the latest language updates to the repo. Check again please 😄

**Comment by Dwynr** [comment]
Thank you so much!! Will merge it as soon as we release the new version.

**Pull request merged**
